2024-11-09 21:32:41,210 | INFO | "test_challenge" выполнен успешно
2024-11-09 21:32:41,210 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-11-09 21:32:41,210 | WARNING | Traceback (most recent call last):
  File "D:\programs\PyProjects\1254554\.venv\UniDZ.py", line 88, in test_run
    runner = Runner(2)
  File "D:\programs\PyProjects\1254554\.venv\UniDZ.py", line 20, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-09 21:32:41,211 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-11-09 21:32:41,211 | WARNING | Traceback (most recent call last):
  File "D:\programs\PyProjects\1254554\.venv\UniDZ.py", line 77, in test_walk
    runner = Runner("Вася", -5)
  File "D:\programs\PyProjects\1254554\.venv\UniDZ.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

